services:
  - type: web
    name: forex-ai-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    runtime: python-3.11.9
    envVars:
      XAI_API_KEY:
        sync: false
      NEWS_API_KEY:
        sync: false
      TELEGRAM_TOKEN:
        sync: false
      ADMIN_USER_ID:
        sync: false
